#!/bin/bash

echo ░▀█▀░█▀█░█▀▀░▀█▀░█▀█░█░░░█░░░█▀▀░█▀▄░█▀▄░█▀▄░█▀▄░█▀▄░█▀▄
echo ░░█░░█░█░▀▀█░░█░░█▀█░█░░░█░░░█▀▀░█▀▄░█▀▄░█▀▄░█▀▄░█▀▄░█▀▄
echo ░▀▀▀░▀░▀░▀▀▀░░▀░░▀░▀░▀▀▀░▀▀▀░▀▀▀░▀░▀░▀░▀░▀░▀░▀░▀░▀░▀░▀░▀

read -p "Press any key to use installerrrrrr"
sudo apt update -y
sudo apt upgrade -y

sudo snap remove thunderbird firefox -y

sudo apt install gnome-tweaks keepassxc npm python3-dev python3-pip python3-setuptools flatpak gnome-software-plugin-flatpak git  -y
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo -y

#firefox
sudo install -d -m 0755 /etc/apt/keyrings 
wget -q https://packages.mozilla.org/apt/repo-signing-key.gpg -O- | sudo tee /etc/apt/keyrings/packages.mozilla.org.asc > /dev/null
gpg -n -q --import --import-options import-show /etc/apt/keyrings/packages.mozilla.org.asc | awk '/pub/{getline; gsub(/^ +| +$/,""); if($0 == "35BAA0B33E9EB396F59CA838C0BA5CE6DC6315A3") print "\nThe key fingerprint matches ("$0").\n"; else print "\nVerification failed: the fingerprint ("$0") does not match the expected one.\n"}'

flatpak install flathub org.mozilla.Thunderbird -y
pip3 install thefuck --user -y
